### ISSUE TITLE
Unable to run the VMs' Environment

### ISSUE THREAD

**Issue by minkione** [djformby/GRFICS#2]
I am using exactly those VMs provided and I setup Virtualbox as explained (e.g. host-only subnet 192.168.95/1/24)

- PLC: 192.168.95.3
- HMI: 192.168.95.5
- SIMULATION: 192.168.95.4

When I run sudo bash run_all.sh (of course, after first running sudo HMI_Simulation_Ubuntu1604_15_x86_64.x86_64) I get:
![image](https://user-images.githubusercontent.com/25242404/46666817-60a71980-cbd0-11e8-8bcf-29a503a1be90.png)

Despite that error, I kept following the README and I ran:

- Log into plc VM, cd into the OpenPLC_v2 directory, and run "sudo nodejs server.js"
- Log into hmi VM, cd into the HMI directory, and run "wine HMI/AdvancedHMI.exe"

However the HMI doesn't get populated/working:

![image](https://user-images.githubusercontent.com/25242404/46666885-9f3cd400-cbd0-11e8-8962-947e5aeefbf3.png)

Do you have any hints where I should start debugging?
I have the feeling that would be better just to setup static IPs for all VMs.... cause grepping on remote_io directory shows some hardcoded IPs...

![image](https://user-images.githubusercontent.com/25242404/46667139-59ccd680-cbd1-11e8-82b1-e40526f2ff15.png)

**Comment by djformby** [comment]
Thanks for reaching out! You're right, static IPs are necessary due to hardcoded IPs in multiple places. I thought the addresses would carry over when imported, but in case they didn't or got overwritten here's what they should be:

PLC VM - 192.168.95.2
HMI VM - 192.168.95.3

The simulation VM pretends to be 6 different remote IO devices, so you need to assign 6 IP address aliases all to the same host-only network interface, ranging from .10 up to .15, as shown in the screenshot below
![image](https://user-images.githubusercontent.com/12502872/46752494-5a29a800-cc8b-11e8-8dea-2ec7141fdf2e.png)

I believe setting all the IP addresses should fix the problem, but let me know if you have any more questions.
